### ISSUE TITLE
Create new OverLeaf page for report

### ISSUE THREAD

**Issue by Joost001** [Joost001/cs678_research#5]

**Comment by jovasque156** [comment]
I just sent the invitation to edit the overleaf project. The template could change since professors will upload one to BB soon.

**Comment by jovasque156** [comment]
I just sent the invitation to edit the overleaf project. The template could change since professors will upload one to BB soon.

**Comment by Joost001** [comment]
Can you add a link to the wiki page on GitHub?

**Comment by jovasque156** [comment]
Done.
